### ISSUE TITLE
PiClock²: Lets hammer out a plugin interface.

### ISSUE THREAD

**Issue by n0bel** [n0bel/PiClock#77]
* First basic question:
  * Use somebody's framework, or just basic python modules with an inherited interface?

* Second basic question:
  * What does it need?
    * Config (global plus module specific config)
    * Place/Position/Size (frame, x, y, width, height)  Is that it?
    * Registry of consumers and providers
      * A plugin isn't "required" to have a display.  It could simply be the WUAPI for example.  This type of plugin could register as a provider for "generic" types of weather data that PiClock formalizes, plus a WU specific data provider for WU specific consumers.

Thoughts?  esp @dankolbrs

**Comment by hsoj95** [comment]
If I was gonna suggest a way to do it, I'd have all of the customization settings in one config files, including the WUAPI keys, the location cords, the radar settings, and other stuff like that. Try and separate operating code completely from configuration. That should make it easier for the user to setup the PiClock for their own use.

**Comment by dankolbrs** [comment]
Someone asked for a rambling-Dan response?

That' probably the way to go @hsoj95 , config could be something like:
```
config:
  keys:
    - wu: <longstringhere>
    - darksky: <somethingelse>
  radar:
    - radar1: 
        location:
          lat: 
          lon:
  clock:
     type: digital
     size:
```
Clock plugins could be just passed the `config["clock"]` configuration, rather than passing around the whole config object. And it could carry over to other types of plugins. There's probably no need to worry about someone writing a malicious plugin that steals your API keys if that's passed in, but no reason to bounce around the whole thing. 

For the questions:
### 1
Is there a global config that would need to be passed along?

I suppose the plugin interface can get as complicated as you'd want it to be. I've toyed with them a couple times, but everything I've come up with works but seems like it's oversimplified and there may be a better way. My [most recent](https://github.com/dankolbrs/wifimon/blob/master/wifimon/scanwifi.py#L18-L30) and what seemed to be simplest was just tossing a couple classes in a plugins directory with standard methods, parsing the files in that directory and importing them, then calling them. It works, not terribly elegant, but I did that just so I could more easily throw data around in different databases on my internal network so there really wasn't complexity there anyway. There's plenty of open source projects on Github that could be scoped out for ideas, which is on my ever growing list of things to check out.

Sounds like there's two plugin infrastructures to consider, data and display.

### 2
This may warrant a larger discussion on how much freedom the plugin is given. I like the idea of PiClock itself handling the layout, and plugins would then be written to operate within the given layout.  Have the same frames that currently exist, and have the plugin use an existing frame. That would limit customization, but may make it easier for others to contribute and write plugins. If that was the way it went I'd like to see two more frames to account for alerts and RSS, but my want itself may indicate there could be later requests to allow more customization and would argue for allowing this *more complicated* customization from plugins from the start.

Having a specific frame layout the plugin is written to would let the plugin writer decide how the plugin will display within the section of the screen, and not have to worry about piecing all frames together. Also would make the config easier, it would get either the `apikeys` module, the `radar` module, etc. The plugin would be given two things when instantiated, the frame for it to occupy (or size and have it return the frame (or the plugin could just pull the size from the frame)), and the relevant config section. Plugins may also require some kind of registration on what data the plugin requires on tick and timer events (see below, I'm thinking raw API return vs an abstracted data backend return on timer events and time being sent on ticks).

Data backends would be different, and probably easier, and from what I remember may account for more of the opened issues. I'm thinking two things can be required from a data plugin:
* Standardized (abstracted) weather return (used by "official" PiClock plugins or current functionality, or to make it easier to write)
* Raw API return
**The raw API return would allow fields not available in all APIs to be pulled by display plugins to prevent the need to constantly update the abstraction, or not accounting for **all** possible APIs.**

Personally, I want to easily change these things and this is where my thinking is coming from:
1. Data in (switch between WU and Darksky, or some other weather API, or my own database, or maybe some combination)
2. Data out (currently I've got it hardcoded sending the API output to database where I can integrate other things or play around with it later, really this would be done with the same infrastructure as above item)
3. Display alerts/RSS, or some other text in a box that is already configured (but not always displayed, controlled by the plugin)

**Comment by n0bel** [comment]
> Someone asked for a rambling-Dan response?
Yup sure did.

How 'bout this for a config.

providers so the apis can be central (sources?) (apis?) (idk)
pages (frames in old terminology)
views which are things to put on a page somewhere
views have common properties like name (plugin name), geometry (where on the page) as well as plugin specific properties.

(i don't think i have it formatted correctly tho, and maybe not even the syntax for yaml)

```
config:
  providers:
    - provider:
        name: wu
        apiKey: 
    - provider:
        name: google-maps
        apiKey:
    - provider:
        name: darksky
        apiKey:
    - provider:
        name: temperature-sensor
  pages:
    - page:
      - view:
          name: radar-wu
          provider: wu
          geometry:
            x: 0
            y: -80%    # % or px negatives mean from bottom
            w: 100px
            h: 200px
          location:
            latitude: -93
            longitude: 45
            zoom: 7   # google maps units
          markers:
            latitude: -93
            longitude: 45
            color: red
      - view:
          name: radar-wu
          provider: wu
          geometry:
            x: 0
            ...
            ...
            ...
      - view:
          name: clock-digital
          geometry:
            x: 30%
            y: 20% 
            w: 100px
            h: 200px
          font: crazy
          fontSize: 40
          formatString: {0:%I:%M\n%S %p}
      - view:
          name: forecast-wu
          geometry:
          ...
          ...
          ...
      - view:
        name: current-conditions-generic
          geometry:
          ....
          ....
          ....
    - page:
      - view:
          name: radar-wu
          provider: wu
          geometry:
            x: 0
            y: -80%    # % or px negatives mean from bottom
            w: 500px
            h: 600px
           location:
             latitude: -93
             longitude: 45
             zoom: 7   # google maps units
           markers:
             latitude: -93
             longitude: 45
           color: red
      - view:
           name: boxed-string
           geometry:
             ...
             ...
             ...
           string: The indoor temperature is !temperature-sensor:sensor1
```
